const HTML_ENTITIES:Record<string,string>={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"};
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>HTML_ENTITIES[c]||c);

function layout(title:string,preheader:string,body:string,cta?:{label:string;url:string}){
 const action=cta?`<div style="margin:28px 0 8px"><a href="${esc(cta.url)}" style="display:inline-block;background:#17151a;color:#fff;text-decoration:none;padding:13px 20px;border-radius:12px;font-weight:800;font-size:14px">${esc(cta.label)}</a></div>`:"";
 return `<!doctype html><html><body style="margin:0;background:#f5f1f3;font-family:Arial,Helvetica,sans-serif;color:#201b20"><div style="display:none;max-height:0;overflow:hidden">${esc(preheader)}</div><table width="100%" cellspacing="0" cellpadding="0" role="presentation"><tr><td align="center" style="padding:28px 12px"><table width="100%" cellspacing="0" cellpadding="0" role="presentation" style="max-width:620px;background:#fff;border:1px solid #eadfe4;border-radius:20px;overflow:hidden;box-shadow:0 12px 35px rgba(55,37,47,.08)"><tr><td style="padding:20px 26px;border-bottom:1px solid #f1e8ec"><div style="font-size:22px;font-weight:900;letter-spacing:-.6px">Beauty<span style="color:#8f63d8">Flow</span></div><div style="margin-top:4px;color:#8b7983;font-size:11px;font-weight:700;letter-spacing:1.5px">BEAUTY · GROOMING · WELLNESS</div></td></tr><tr><td style="padding:30px 26px"><h1 style="margin:0 0 14px;font-size:26px;line-height:1.2">${esc(title)}</h1>${body}${action}</td></tr><tr><td style="padding:18px 26px;background:#fbf8f9;color:#94828b;font-size:11px;line-height:1.6">Това съобщение е изпратено автоматично от BeautyFlow. Моля, не изпращайте чувствителни данни в отговор на този email.</td></tr></table></td></tr></table></body></html>`;
}
function row(label:string,value:unknown){return `<tr><td style="padding:9px 0;color:#8c7a83;font-size:12px;width:34%">${esc(label)}</td><td style="padding:9px 0;font-size:13px;font-weight:800;text-align:right">${esc(value)}</td></tr>`}
function details(rows:[string,unknown][]){return `<table width="100%" cellspacing="0" cellpadding="0" style="margin:20px 0;background:#faf7f8;border:1px solid #eee3e7;border-radius:14px;padding:8px 14px">${rows.map(r=>row(r[0],r[1])).join("")}</table>`}

export function ownerMessageEmail(x:{ownerName:string;subject:string;message:string}){
 const paragraphs=x.message.split(/\n\s*\n/).map(p=>`<p style="color:#66565f;line-height:1.7;white-space:pre-line">${esc(p)}</p>`).join("");
 return {subject:x.subject,text:`Здравейте, ${x.ownerName}!\n\n${x.message}\n\nBeautyFlow · ВЕЛКРОН ЕООД`,html:layout(x.subject,x.message.slice(0,120),`<p style="color:#66565f;line-height:1.7">Здравейте, <strong>${esc(x.ownerName)}</strong>!</p>${paragraphs}<p style="margin-top:24px;color:#8a7981;font-size:12px">BeautyFlow · Оператор: ВЕЛКРОН ЕООД</p>`)};
}

export function accessStatusEmail(x:{ownerName:string;businessName:string;status:"suspend"|"activate"|"renew";until?:string}){
 const content={suspend:{subject:"BeautyFlow — достъпът е временно спрян",title:"Достъпът е временно спрян",message:`Достъпът до ${x.businessName} е временно спрян. За въпроси се свържете с екипа на BeautyFlow.`},activate:{subject:"BeautyFlow — достъпът е възстановен",title:"Достъпът е възстановен",message:`Достъпът до ${x.businessName} е активиран отново. Вече можете да влезете в профила си.`},renew:{subject:"BeautyFlow — абонаментът е подновен",title:"Абонаментът е подновен",message:`Достъпът до ${x.businessName} е подновен до ${x.until||"посочената дата"}.`}}[x.status];
 return {subject:content.subject,text:`Здравейте, ${x.ownerName}. ${content.message}`,html:layout(content.title,content.message,`<p style="color:#66565f;line-height:1.7">Здравейте, <strong>${esc(x.ownerName)}</strong>.</p><p style="color:#66565f;line-height:1.7">${esc(content.message)}</p>${details([["Бизнес",x.businessName],["Статус",content.title],...(x.until?[["Активен до",x.until] as [string,string]]:[])])}`)};
}

export function requestReceivedEmail(x:{ownerName:string;businessName:string}){return {subject:"BeautyFlow — получихме заявката Ви",text:`Здравейте, ${x.ownerName}. Получихме заявката за ${x.businessName}. Ще получите нов email след преглед.`,html:layout("Заявката Ви е получена","BeautyFlow получи заявката Ви.",`<p style="margin:0;color:#66565f;line-height:1.7">Здравейте, <strong>${esc(x.ownerName)}</strong>.</p><p style="color:#66565f;line-height:1.7">Получихме заявката за <strong>${esc(x.businessName)}</strong>. Ще я прегледаме и ще Ви изпратим нов email веднага щом има решение.</p><div style="margin-top:18px;padding:14px;border-radius:12px;background:#f3edf9;color:#5f3d8c;font-size:13px"><strong>Какво следва?</strong><br>При одобрение ще получите защитен линк, чрез който да зададете парола и да настроите профила си.</div>`)}}

export function newRequestOwnerEmail(x:{ownerName:string;businessName:string;email:string;phone:string;city:string;category:string}){return {subject:`Нова BeautyFlow заявка — ${x.businessName}`,text:`Нова заявка: ${x.businessName}\n${x.ownerName}\n${x.email}\n${x.phone}\n${x.city}\n${x.category}`,html:layout("Нова заявка за достъп","Има нов бизнес, който чака преглед.",`<p style="margin:0;color:#66565f;line-height:1.7">Има нова заявка за BeautyFlow, която чака преглед.</p>${details([["Бизнес",x.businessName],["Име",x.ownerName],["Email",x.email],["Телефон",x.phone],["Град",x.city],["Категория",x.category]])}`)}}

export function approvedEmail(x:{ownerName:string;businessName:string;resetUrl:string}){return {subject:"BeautyFlow — достъпът Ви е одобрен ✅",text:`Здравейте, ${x.ownerName}. ${x.businessName} е одобрен. Задайте парола: ${x.resetUrl}`,html:layout("Добре дошли в BeautyFlow ✨","Достъпът Ви е одобрен.",`<p style="margin:0;color:#66565f;line-height:1.7">Здравейте, <strong>${esc(x.ownerName)}</strong>.</p><p style="color:#66565f;line-height:1.7">Заявката за <strong>${esc(x.businessName)}</strong> е одобрена. Профилът Ви е създаден и остава само да зададете парола.</p><div style="padding:14px;border-radius:12px;background:#eef8f1;color:#356447;font-size:13px"><strong>След вход:</strong> добавете услугите, работното време, екипа и публичната информация. BeautyFlow ще използва тези настройки, за да изчислява свободните часове автоматично.</div>`,{label:"Задай парола и влез",url:x.resetUrl})}}

export function rejectedEmail(x:{ownerName:string;businessName:string}){return {subject:"BeautyFlow — отговор по заявката",text:`Здравейте, ${x.ownerName}. На този етап не можем да активираме достъп за ${x.businessName}.`,html:layout("Отговор по заявката Ви","Има решение по BeautyFlow заявката Ви.",`<p style="margin:0;color:#66565f;line-height:1.7">Здравейте, <strong>${esc(x.ownerName)}</strong>.</p><p style="color:#66565f;line-height:1.7">Благодарим за интереса към BeautyFlow. На този етап не можем да активираме достъп за <strong>${esc(x.businessName)}</strong>.</p><p style="color:#8a7981;font-size:13px;line-height:1.6">Това не пречи да кандидатствате отново при промяна на информацията или условията.</p>`)}}

export function customerBookingEmail(x:{customerName:string;salonName:string;serviceName:string;date:string;time:string;mapUrl?:string|null}){return {subject:`BeautyFlow — часът Ви в ${x.salonName} е потвърден`,text:`${x.customerName}, часът Ви е потвърден. ${x.salonName}, ${x.serviceName}, ${x.date}, ${x.time}.${x.mapUrl?` Локация: ${x.mapUrl}`:""}`,html:layout("Часът Ви е запазен ✅","Вашата BeautyFlow резервация е потвърдена.",`<p style="margin:0;color:#66565f;line-height:1.7">Здравейте, <strong>${esc(x.customerName)}</strong>. Вашата резервация е потвърдена.</p>${details([["Салон",x.salonName],["Услуга",x.serviceName],["Дата",x.date],["Час",x.time]])}<p style="color:#8a7981;font-size:13px;line-height:1.6">Запазете този email, за да имате информацията за часа си под ръка.</p>`,x.mapUrl?{label:"Локация на салона",url:x.mapUrl}:undefined)}}

export function adminBookingEmail(x:{salonName:string;customerName:string;phone:string;email?:string|null;serviceName:string;date:string;time:string;note?:string|null}){return {subject:`Ново записване — ${x.date} в ${x.time}`,text:`Ново записване в ${x.salonName}\n${x.customerName}\n${x.phone}\n${x.serviceName}\n${x.date} ${x.time}${x.note?`\nБележка: ${x.note}`:""}`,html:layout("Имате ново записване","Нов клиент се записа през BeautyFlow.",`<p style="margin:0;color:#66565f;line-height:1.7">BeautyFlow добави нов час в графика на <strong>${esc(x.salonName)}</strong>.</p>${details([["Клиент",x.customerName],["Телефон",x.phone],["Email",x.email||"—"],["Услуга",x.serviceName],["Дата",x.date],["Час",x.time],["Бележка",x.note||"—"]])}<p style="color:#8a7981;font-size:13px;line-height:1.6">Резервацията вече е видима в админ панела.</p>`)}}

export function bookingVerificationEmail(x:{code:string;salonName:string}){return {subject:`BeautyFlow — код за потвърждение: ${x.code}`,text:`Кодът Ви за потвърждение в ${x.salonName} е ${x.code}. Валиден е 10 минути.`,html:layout("Потвърдете своя email","Код за потвърждение на BeautyFlow.",`<p style="margin:0;color:#66565f;line-height:1.7">За да завършите записването си в <strong>${esc(x.salonName)}</strong>, въведете този код:</p><div style="margin:22px 0;padding:18px;border-radius:14px;background:#f3edf8;text-align:center;font-size:32px;letter-spacing:8px;font-weight:900;color:#5f3d8c">${esc(x.code)}</div><p style="color:#8a7981;font-size:13px">Кодът е валиден 10 минути. Ако не сте заявявали час, игнорирайте този email.</p>`)} }
