"use client";

import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import PublicNav from "@/components/PublicNav";
import Footer from "@/components/Footer";
import { loadDemoState,saveDemoState } from "@/lib/beautyflow/demoStore";
import { appointmentEnd,getAvailableSlots } from "@/lib/beautyflow/slots";
import type { BeautyFlowDemoState } from "@/lib/beautyflow/types";

function isoDate(offset=0){const d=new Date();d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)}

export default function DemoSalon(){
 const[state,setState]=useState<BeautyFlowDemoState|null>(null);const[serviceId,setServiceId]=useState("");const[date,setDate]=useState(isoDate(1));const[time,setTime]=useState("");const[name,setName]=useState("");const[phone,setPhone]=useState("");const[done,setDone]=useState(false);
 useEffect(()=>{const s=loadDemoState();setState(s);setServiceId(s.services.find(x=>x.active)?.id||"")},[]);
 const service=state?.services.find(s=>s.id===serviceId);
 const slots=useMemo(()=>state&&service?getAvailableSlots({date,service,workingHours:state.workingHours,appointments:state.appointments,timeOff:state.timeOff,settings:state.settings}):[],[state,service,date]);
 useEffect(()=>{if(time&&!slots.includes(time))setTime("")},[slots,time]);
 if(!state)return <main className="page"><PublicNav/><div className="container section">Зареждане...</div></main>;
 function book(){if(!service||!time||!name.trim()||!phone.trim())return;const appointment={id:`booking-${Date.now()}`,serviceId:service.id,date,start:time,end:appointmentEnd(time,service),customerName:name.trim(),customerPhone:phone.trim(),status:"confirmed" as const,createdAt:new Date().toISOString()};const next={...state,appointments:[...state.appointments,appointment]};setState(next);saveDemoState(next);setDone(true)}
 if(done)return <main className="page booking-demo-page"><PublicNav/><section className="container booking-success"><div className="success-mark">✓</div><span className="eyebrow">ГОТОВО</span><h1>Часът е запазен.</h1><p>{name}, очакваме те на <strong>{date}</strong> в <strong>{time}</strong> за <strong>{service?.name}</strong>.</p><div className="action-row"><Link className="btn btn-primary" href="/admin/bookings">Виж в админ панела</Link><button className="btn btn-light" onClick={()=>{setDone(false);setTime("");setName("");setPhone("")}}>Ново записване</button></div></section><Footer/></main>;
 return <main className="page booking-demo-page"><PublicNav/><section className="booking-profile-head"><div className="container"><span className="eyebrow">ДЕМО ПРОФИЛ</span><h1>{state.business.name}</h1><p>{state.business.description}</p><div className="profile-meta"><span>📍 {state.business.city}</span><span>✦ {state.business.category}</span></div></div></section><section className="container booking-flow"><div className="booking-step"><span>1</span><div><h2>Избери услуга</h2><p>Продължителността определя кои часове са реално свободни.</p></div></div><div className="public-service-grid">{state.services.filter(s=>s.active).map(s=><button type="button" className={`public-service-card ${serviceId===s.id?"selected":""}`} key={s.id} onClick={()=>{setServiceId(s.id);setTime("")}}><strong>{s.name}</strong><span>{s.durationMin} мин · {s.price.toFixed(2)} лв.</span>{s.bufferMin>0&&<small>+ {s.bufferMin} мин подготовка</small>}</button>)}</div><div className="booking-step"><span>2</span><div><h2>Избери ден</h2><p>Почивните дни и изключенията се скриват автоматично.</p></div></div><div className="date-strip">{Array.from({length:14},(_,i)=>isoDate(i+1)).map(d=><button type="button" key={d} className={date===d?"selected":""} onClick={()=>{setDate(d);setTime("")}}><strong>{new Date(`${d}T12:00:00`).toLocaleDateString("bg-BG",{weekday:"short"})}</strong><span>{new Date(`${d}T12:00:00`).getDate()}</span></button>)}</div><div className="booking-step"><span>3</span><div><h2>Свободни часове</h2><p>{service?`BeautyFlow търси ${service.durationMin + service.bufferMin} последователни свободни минути.`:"Първо избери услуга."}</p></div></div><div className="public-slot-grid">{slots.map(s=><button type="button" className={time===s?"selected":""} key={s} onClick={()=>setTime(s)}>{s}</button>)}{slots.length===0&&<div className="no-slots">Няма свободни часове за този ден.</div>}</div><div className="booking-step"><span>4</span><div><h2>Твоите данни</h2><p>Без регистрация и без излишни стъпки.</p></div></div><div className="booking-customer panel-card"><div className="form-grid"><div className="field"><label>Име</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Име и фамилия"/></div><div className="field"><label>Телефон</label><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="08..."/></div></div><div className="booking-summary"><span>Избрано</span><strong>{service?.name||"–"} · {date} · {time||"избери час"}</strong></div><button className="btn btn-primary booking-submit" disabled={!service||!time||!name.trim()||!phone.trim()} onClick={book}>Потвърди записването</button></div></section><Footer/></main>
}
