import{NextResponse}from"next/server";import{createHash}from"crypto";import{getSupabaseAdmin}from"@/lib/supabaseAdmin";import{toMinutes,fromMinutes,overlaps}from"@/lib/beautyflow/time";import{minutesUntilSofia,sofiaNow}from"@/lib/beautyflow/clock";import{canCreateBeautyFlowBookings}from"@/lib/beautyflow/subscription";
const c=(v:unknown,n=160)=>String(v||"").replace(/[<>]/g,"").trim().slice(0,n);const phoneKey=(v:string)=>v.replace(/[^0-9+]/g,"");export async function POST(req:Request){try{const b=await req.json();if(c(b.website,120))return NextResponse.json({ok:true,message:"Часът е запазен успешно."});const salonId=c(b.salonId,50),serviceId=c(b.serviceId,50),requestedStaffId=c(b.staffId,50)||null,date=c(b.date,10),startTime=c(b.startTime,5),customerName=c(b.customerName,90),customerPhone=c(b.customerPhone,10),phoneNormalized=phoneKey(customerPhone),customerEmail=c(b.customerEmail,140).toLowerCase()||null,verificationId=c(b.verificationId,60),verificationCode=c(b.verificationCode,6),note=c(b.note,500)||null,acceptedTerms=String(b.acceptedTerms||"")==="yes"||b.acceptedTerms===true;if(!salonId||!serviceId||!date||!startTime||!customerName)return NextResponse.json({message:"Провери данните за записването."},{status:400});if(!/^0\d{9}$/.test(phoneNormalized))return NextResponse.json({message:"Телефонът трябва да е български номер от 10 цифри и да започва с 0."},{status:400});if(!customerEmail||!/^\S+@\S+\.\S{2,}$/i.test(customerEmail))return NextResponse.json({message:"Email адресът е задължителен и трябва да е валиден."},{status:400});if(!acceptedTerms)return NextResponse.json({message:"За да запазиш час, трябва да приемеш Общите условия и да се запознаеш с Политиката за поверителност."},{status:400});if(!verificationId||!/^[0-9a-f-]{36}$/i.test(verificationId)||!/^[0-9]{6}$/.test(verificationCode))return NextResponse.json({message:"Потвърди email адреса си с 6-цифрения код."},{status:403});const db=getSupabaseAdmin();const codeHash=createHash("sha256").update(verificationCode).digest("hex");const{data:verification}=await db.from("booking_email_verifications").select("id,email,code_hash,expires_at,consumed_at,attempts").eq("id",verificationId).eq("salon_id",salonId).maybeSingle();if(!verification||verification.email!==customerEmail||verification.consumed_at||new Date(verification.expires_at).getTime()<Date.now()||verification.code_hash!==codeHash){if(verification?.id)await db.from("booking_email_verifications").update({attempts:Number(verification.attempts||0)+1}).eq("id",verification.id);return NextResponse.json({message:"Невалиден или изтекъл код за потвърждение. Поискай нов код."},{status:403});}const weekday=new Date(`${date}T12:00:00`).getDay();
 const[{data:service},{data:salon},{data:settings},{data:staffRows},{data:serviceLinks},{data:staffHours},{data:staffOff},{data:salonHours},{data:salonOff}]=await Promise.all([
  db.from("services").select("id,name,duration_min,buffer_min,price").eq("id",serviceId).eq("salon_id",salonId).eq("active",true).maybeSingle(),db.from("salons").select("name,owner_id,active,map_location,address,subscription_status,subscription_ends_at,trial_ends_at").eq("id",salonId).maybeSingle(),db.from("booking_settings").select("min_notice_hours,notify_new_booking").eq("salon_id",salonId).maybeSingle(),db.from("staff").select("id,name").eq("salon_id",salonId).eq("active",true),db.from("staff_services").select("staff_id").eq("salon_id",salonId).eq("service_id",serviceId),db.from("staff_working_hours").select("*").eq("salon_id",salonId).eq("weekday",weekday),db.from("staff_time_off").select("*").eq("salon_id",salonId).eq("off_date",date),db.from("working_hours").select("*").eq("salon_id",salonId).eq("weekday",weekday).maybeSingle(),db.from("time_off").select("*").eq("salon_id",salonId).eq("off_date",date)
 ]);if(!service||!salon?.active)return NextResponse.json({message:"Услугата не е налична."},{status:409});if(!canCreateBeautyFlowBookings(salon))return NextResponse.json({message:"Онлайн записването за този салон временно не е достъпно."},{status:403});
 const{data:customerFlags}=await db.from("salon_customers").select("status,phone_normalized,email_normalized,customer_email").eq("salon_id",salonId).eq("status","blacklist");if((customerFlags||[]).some((x:any)=>x.phone_normalized===phoneNormalized||String(x.email_normalized||x.customer_email||"").toLowerCase()===customerEmail))return NextResponse.json({message:"Онлайн записване с този телефон или email не е достъпно. Моля, свържете се директно със салона."},{status:403});
 const local=sofiaNow(),today=`${local.year}-${String(local.month).padStart(2,"0")}-${String(local.day).padStart(2,"0")}`;const{data:ownBookings}=await db.from("appointments").select("appointment_date,start_time,status,created_at").eq("salon_id",salonId).eq("customer_phone_normalized",phoneNormalized).gte("appointment_date",today).in("status",["confirmed"]).order("created_at",{ascending:false});const own=ownBookings||[];if(own.some((x:any)=>x.appointment_date===date&&String(x.start_time).slice(0,5)===startTime))return NextResponse.json({message:"Вече има записан такъв час с този телефон."},{status:409});if(own.length>=3)return NextResponse.json({message:"С този телефон вече има 3 активни бъдещи записвания. За нов час се свържи със салона."},{status:429});const newest=own[0]?.created_at?new Date(own[0].created_at).getTime():0;if(newest&&Date.now()-newest<90_000)return NextResponse.json({message:"Изчакай 90 секунди преди да направиш още едно записване."},{status:429});
 const minNotice=Math.max(Number(settings?.min_notice_hours||3)*60,180);if(minutesUntilSofia(date,startTime)<minNotice){const noticeLabel=minNotice>=1440?`${Math.round(minNotice/1440)} ${Math.round(minNotice/1440)===1?"ден":"дни"}`:minNotice<60?`${minNotice} мин.`:`${Math.round(minNotice/60)} ч.`;return NextResponse.json({message:`Този салон приема онлайн записвания най-късно ${noticeLabel} предварително.`},{status:409});}
 if((salonOff||[]).some((x:any)=>x.all_day))return NextResponse.json({message:"Салонът не работи на тази дата."},{status:409});const linked=new Set((serviceLinks||[]).map((x:any)=>x.staff_id));let candidates=(staffRows||[]).filter((s:any)=>linked.size===0||linked.has(s.id));if(requestedStaffId)candidates=candidates.filter((s:any)=>s.id===requestedStaffId);if(!candidates.length)return NextResponse.json({message:"Няма активен специалист за тази услуга."},{status:409});
 const start=toMinutes(startTime),rawEnd=start+Number(service.duration_min)+Number(service.buffer_min||0),end=fromMinutes(Math.min(rawEnd,1439));const{data:existing}=await db.from("appointments").select("start_time,end_time,staff_id").eq("salon_id",salonId).eq("appointment_date",date).neq("status","cancelled");const globalOff=(salonOff||[]).filter((x:any)=>!x.all_day&&x.start_time&&x.end_time).map((x:any)=>[toMinutes(x.start_time),toMinutes(x.end_time)] as [number,number]);let chosen:any=null;
 for(const st of candidates){const h=(staffHours||[]).find((x:any)=>x.staff_id===st.id)||salonHours;if(!h?.enabled)continue;const hs=toMinutes(h.start_time),he=toMinutes(h.end_time);if(start<hs||start+Number(service.duration_min)+Number(service.buffer_min||0)>he)continue;const ownOff=(staffOff||[]).filter((x:any)=>x.staff_id===st.id);if(ownOff.some((x:any)=>x.all_day))continue;const offBlocks=[...globalOff,...ownOff.filter((x:any)=>!x.all_day&&x.start_time&&x.end_time).map((x:any)=>[toMinutes(x.start_time),toMinutes(x.end_time)] as [number,number])];if(offBlocks.some(([a,b])=>overlaps(start,rawEnd,a,b)))continue;const collision=(existing||[]).some((a:any)=>(!a.staff_id||a.staff_id===st.id)&&overlaps(start,rawEnd,toMinutes(a.start_time),toMinutes(a.end_time)));if(collision)continue;chosen=st;break}
 if(!chosen)return NextResponse.json({message:"Този час току-що беше зает. Избери друг."},{status:409});const appointment={salon_id:salonId,service_id:serviceId,staff_id:chosen.id,appointment_date:date,start_time:startTime,end_time:end,customer_name:customerName,customer_phone:customerPhone,customer_phone_normalized:phoneNormalized,customer_email:customerEmail,note,status:"confirmed"};let insertResult=await db.from("appointments").insert({...appointment,terms_accepted_at:new Date().toISOString()}).select("id").single();if(insertResult.error&&/terms_accepted_at|schema cache|column/i.test(insertResult.error.message||"")){insertResult=await db.from("appointments").insert(appointment).select("id").single()}if(insertResult.error||!insertResult.data?.id){console.error("BeautyFlow booking insert failed",insertResult.error);return NextResponse.json({message:`Не успяхме да запазим часа: ${insertResult.error?.message||"неизвестна грешка"}`},{status:500})}
 const settledAt=new Date().toISOString();
 // IMPORTANT: the appointment is already safely stored at this point. Never block the
 // client success response on secondary profile/verification/email work.
 void Promise.allSettled([
  db.from("booking_email_verifications").update({verified_at:settledAt,consumed_at:settledAt}).eq("id",verificationId),
  db.from("salon_customers").upsert({salon_id:salonId,phone_normalized:phoneNormalized,email_normalized:customerEmail,customer_name:customerName,customer_phone:customerPhone,customer_email:customerEmail,status:"regular",updated_at:settledAt},{onConflict:"salon_id,phone_normalized"})
 ]).catch(e=>console.error("BeautyFlow post-booking cleanup failed",e));
 return NextResponse.json({ok:true,message:"Часът е запазен успешно.",appointmentId:insertResult.data.id,staffId:chosen.id,staffName:chosen.name});}catch(e){return NextResponse.json({message:e instanceof Error?`Възникна техническа грешка: ${e.message}`:"Възникна техническа грешка при записването."},{status:500})}}
