import { NextResponse } from "next/server";
import { revalidateTag } from "next/cache";
import { requirePlatformOwner } from "@/lib/ownerAuth";

type Frame={id:string;x:number;y:number;width:number;height:number;media_url?:string;media_type?:"image"|"video";layer?:"background"|"behind"|"front";animation?:string;fit?:"cover"|"contain";media_x?:number;media_y?:number;media_scale?:number;shape?:"rounded"|"pill"|"cut"|"organic"|"soft"|"torn";design_height?:number};
type Frames=Record<string,Frame[]>;
const defaults={background_url:"/brand/beautyflow-background.png" as string|null,background_position:"center top",overlay_opacity:0,page_frames:{} as Frames};
function safeFrames(raw:unknown):Frames{if(!raw||typeof raw!=="object")return{};const out:Frames={};for(const[page,list]of Object.entries(raw as Record<string,unknown>)){if(!Array.isArray(list))continue;out[page]=list.slice(0,100).map((f:any)=>({id:String(f?.id||`frame_${Math.random().toString(36).slice(2)}`),x:Number(f?.x)||0,y:Number(f?.y)||0,width:Math.max(4,Number(f?.width)||20),height:Math.max(4,Number(f?.height)||20),media_url:f?.media_url?String(f.media_url):(f?.image_url?String(f.image_url):undefined),media_type:f?.media_type==="video"?"video":"image",layer:f?.layer==="front"?"front":f?.layer==="background"?"background":"behind",animation:["none","float","reveal-left","reveal-right","reveal-up","pulse"].includes(String(f?.animation))?String(f.animation):"none",fit:f?.fit==="contain"?"contain":"cover",media_x:Math.max(0,Math.min(100,Number(f?.media_x??50))),media_y:Math.max(0,Math.min(100,Number(f?.media_y??50))),media_scale:Math.max(25,Math.min(400,Number(f?.media_scale??100))),shape:["rounded","pill","cut","organic","soft","torn"].includes(String(f?.shape))?f.shape:"rounded",design_height:Math.max(600,Math.min(5000,Number(f?.design_height)||2200))}))}return out}
export async function GET(req:Request){const auth=await requirePlatformOwner(req);if(!auth.ok)return NextResponse.json({message:auth.message},{status:auth.status});const{data,error}=await auth.admin.from("platform_design_settings").select("background_url,background_position,overlay_opacity,page_frames").eq("id",1).maybeSingle();if(error){const old=await auth.admin.from("platform_design_settings").select("background_url,background_position,overlay_opacity").eq("id",1).maybeSingle();return NextResponse.json({...defaults,...(old.data||{}),page_frames:{},setupRequired:true,message:"Пусни SQL файла platform-design-v2.37.sql в Supabase, за да активираш рамките по страници."})}return NextResponse.json({...defaults,...data,page_frames:safeFrames(data?.page_frames)})}
export async function POST(req:Request){const auth=await requirePlatformOwner(req);if(!auth.ok)return NextResponse.json({message:auth.message},{status:auth.status});try{const form=await req.formData();const position=String(form.get("background_position")||"center top");let backgroundUrl=String(form.get("background_url")||"").trim()||null;let pageFrames:Frames={};try{pageFrames=safeFrames(JSON.parse(String(form.get("page_frames")||"{}")))}catch{}
 async function upload(file:File,pathPrefix:string){if(!file.type.startsWith("image/")&&!file.type.startsWith("video/"))throw new Error("Избери снимка или видео файл.");const mime=["image/jpeg","image/png","image/webp","image/gif","video/mp4","video/webm","video/quicktime"];try{await auth.admin.storage.createBucket("platform-assets",{public:true,allowedMimeTypes:mime})}catch{}try{await (auth.admin.storage as any).updateBucket("platform-assets",{public:true,allowedMimeTypes:mime,fileSizeLimit:null})}catch{}const ext=(file.name.split(".").pop()|| (file.type.startsWith("video/")?"mp4":"png")).replace(/[^a-z0-9]/gi,"").toLowerCase();const path=`design/${pathPrefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}.${ext}`;const bytes=Buffer.from(await file.arrayBuffer());const up=await auth.admin.storage.from("platform-assets").upload(path,bytes,{contentType:file.type,upsert:false});if(up.error)throw new Error(up.error.message);return auth.admin.storage.from("platform-assets").getPublicUrl(path).data.publicUrl}
 const background=form.get("background_file");if(background instanceof File&&background.size>0)backgroundUrl=await upload(background,"global-background");
 for(const[key,val]of form.entries()){if(!key.startsWith("frame_file__")||!(val instanceof File)||val.size===0)continue;const id=key.slice("frame_file__".length);const url=await upload(val,`frame-${id.replace(/[^a-z0-9_-]/gi,"")}`);for(const list of Object.values(pageFrames)){const f=list.find(x=>x.id===id);if(f){f.media_url=url;f.media_type=val.type.startsWith("video/")?"video":"image";break}}}
 const{error}=await auth.admin.from("platform_design_settings").upsert({id:1,background_url:backgroundUrl,background_position:position,overlay_opacity:0,page_frames:pageFrames,updated_at:new Date().toISOString()},{onConflict:"id"});if(error)return NextResponse.json({message:`${error.message} — пусни platform-design-v2.37.sql в Supabase.`},{status:400});revalidateTag("beautyflow-design");return NextResponse.json({message:"Визията е запазена.",background_url:backgroundUrl,background_position:position,overlay_opacity:0,page_frames:pageFrames})}catch(e){return NextResponse.json({message:e instanceof Error?e.message:"Грешка при запис."},{status:500})}}
