"use client";
import Link from"next/link";
import{useEffect,useState}from"react";
import{useRouter}from"next/navigation";
import{supabase}from"@/lib/supabase";
export default function PublicNav(){
 const[open,setOpen]=useState(false),[panel,setPanel]=useState<string|null>(null),[authReady,setAuthReady]=useState(false);const router=useRouter();
 useEffect(()=>{let alive=true;(async()=>{try{const{data}=await supabase.auth.getSession();const user=data.session?.user;if(!user)return;const{data:owner}=await supabase.from("platform_owners").select("user_id").eq("user_id",user.id).maybeSingle();if(alive)setPanel(owner?"/owner":"/admin")}finally{if(alive){setAuthReady(true);window.dispatchEvent(new Event("beautyflow:auth-ready"))}}})();return()=>{alive=false}},[]);
 const close=()=>setOpen(false);async function logout(){close();await supabase.auth.signOut();setPanel(null);router.replace("/");router.refresh()}
 return <header className={`nav bf-public-nav-v257 ${open?"menu-open":""}`}><div className="nav-inner"><Link href="/" className="brand" onClick={close}><img className="brand-logo" src="/beautyflow-logo-circle.webp" alt="BeautyFlow"/><span className="brand-copy"><span className="brand-word">Beauty<span>Flow</span></span><small>Bookings made beautiful</small></span></Link><nav className={`nav-links ${open?"is-open":""}`}><Link href="/" onClick={close}>Начало</Link><Link href="/salons" onClick={close}>Салони</Link><Link href="/specialists" onClick={close}>Специалисти</Link><Link href="/discover" onClick={close}>Открий</Link><Link href="/how-it-works" onClick={close}>Как работи</Link><Link href="/about" onClick={close}>За нас</Link><Link href="/contact" onClick={close}>Контакти</Link><div className="mobile-auth-links">{authReady&&(panel?<><Link href={panel} className="mobile-login" onClick={close}>Отвори панела</Link><button type="button" className="mobile-logout" onClick={logout}>Изход</button></>:<><Link href="/login" className="mobile-login" onClick={close}>Вход</Link><Link href="/register-salon" className="mobile-business" onClick={close}>Заяви достъп</Link></>)}</div></nav><div className="nav-actions">{authReady&&(panel?<><Link href={panel} className="nav-login">Панел</Link><button type="button" className="btn btn-primary nav-cta nav-logout" onClick={logout}>Изход</button></>:<><Link href="/login" className="nav-login">Вход</Link><Link href="/register-salon" className="btn btn-primary nav-cta">Заяви достъп</Link></>)}<button className="menu-btn" type="button" aria-label="Меню" aria-expanded={open} onClick={()=>setOpen(!open)}><span/><span/><span/></button></div></div></header>
}
