"use client";
import {useEffect,useState,useRef} from "react";
import AdminShell from "@/components/admin/AdminShell";
import {useBusiness} from "@/lib/beautyflow/useBusiness";
import {supabase} from "@/lib/supabase";
import LoadingScreen from "@/components/LoadingScreen";

type CheckResult={date:string;slots:any[];checked:boolean;loading:boolean;message:string};
export default function Waitlist(){
 const{business,loading}=useBusiness();const[list,setList]=useState<any[]>([]);const[msg,setMsg]=useState("");const[checks,setChecks]=useState<Record<string,CheckResult>>({});const[listLoading,setListLoading]=useState(true);const[assigning,setAssigning]=useState("");const[assignMessages,setAssignMessages]=useState<Record<string,string>>({});const activeAssignment=useRef(false);const[removing,setRemoving]=useState("");
 async function load(preserveMessage=false){if(!business)return;setListLoading(true);try{const{data:{session}}=await supabase.auth.getSession();const r=await fetch(`/api/business/waitlist?salonId=${encodeURIComponent(business.id)}`,{headers:{Authorization:`Bearer ${session?.access_token||""}`},cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.message||"Не успяхме да заредим списъка.");if(!preserveMessage)setMsg("");setList(j.items||[])}catch(e){setMsg(e instanceof Error?e.message:"Не успяхме да заредим списъка.");setList([])}finally{setListLoading(false)}}
 useEffect(()=>{setListLoading(true);setChecks({});void load()},[business?.id]);
 async function find(x:any,date:string){if(!business||!date)return;setChecks(v=>({...v,[x.id]:{date,slots:[],checked:false,loading:true,message:""}}));try{const q=new URLSearchParams({salonId:business.id,serviceId:x.service_id,date});if(x.staff_id)q.set("staffId",x.staff_id);const r=await fetch(`/api/public/availability?${q}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.message||"Не успяхме да проверим свободните часове.");const slots=(j.timeline||[]).filter((y:any)=>y.status==="available");setChecks(v=>({...v,[x.id]:{date,slots,checked:true,loading:false,message:j.message||""}}))}catch(e){setChecks(v=>({...v,[x.id]:{date,slots:[],checked:true,loading:false,message:e instanceof Error?e.message:"Грешка при проверката."}}))}}
 async function assign(x:any,date:string,time:string,staffId?:string){if(!business||activeAssignment.current)return;activeAssignment.current=true;setAssigning(x.id);setAssignMessages(v=>({...v,[x.id]:""}));try{const{data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Сесията е изтекла. Влез отново.");const r=await fetch("/api/business/waitlist-assign",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({id:x.id,date,time,staffId})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||"Не успяхме да запишем клиента.");setMsg(j.message);await load(true)}catch(error){setAssignMessages(v=>({...v,[x.id]:error instanceof Error?error.message:"Не успяхме да запишем клиента."}))}finally{activeAssignment.current=false;setAssigning("")}}
 async function remove(x:any){if(!confirm(`Да премахна ли ${x.customer_name} от списъка за изчакване?`))return;setRemoving(x.id);try{const{data:{session}}=await supabase.auth.getSession();const r=await fetch("/api/business/waitlist",{method:"DELETE",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token||""}`},body:JSON.stringify({id:x.id})});const j=await r.json();if(!r.ok)throw new Error(j.message||"Не успяхме да премахнем клиента.");setMsg(j.message);await load(true)}catch(e){setMsg(e instanceof Error?e.message:"Грешка при премахване.")}finally{setRemoving("")}}
 if(loading||listLoading)return <LoadingScreen title="Зареждане..." subtitle="Зареждаме списъка за изчакване"/>;
 return <AdminShell><header className="dash-header"><div><span className="eyebrow">ИЗЧАКВАНЕ</span><h1>Списък за изчакване</h1><p>Избери ден от желания от клиента период и провери свободните часове за услугата.</p></div></header>{msg&&<p className="form-message bf-strong-message">{msg}</p>}<section className="dash-card"><div className="bf-waitlist-admin">{list.length===0?<div className="dash-empty">Няма чакащи клиенти.</div>:list.map(x=><WaitRow key={x.id} x={x} check={checks[x.id]} find={find} assign={assign} remove={remove} removing={removing===x.id} assigning={assigning===x.id} assignmentMessage={assignMessages[x.id]||""}/>)}</div></section></AdminShell>
}
function WaitRow({x,check,find,assign,remove,removing,assigning,assignmentMessage}:{x:any;check?:CheckResult;find:(x:any,date:string)=>void;assign:(x:any,date:string,time:string,staffId?:string)=>void;remove:(x:any)=>void;removing:boolean;assigning:boolean;assignmentMessage:string}){
 const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Sofia",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const today=["year","month","day"].map(type=>parts.find(p=>p.type===type)?.value).join("-");const first=String(x.date_from)>today?String(x.date_from):today;const last=String(x.date_to||x.date_from);const[date,setDate]=useState(first);const dates:string[]=[];for(let current=first;current<=last&&dates.length<7;){dates.push(current);const d=new Date(`${current}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+1);current=d.toISOString().slice(0,10)}const[selected,setSelected]=useState<{time:string;staffId:string;staffName?:string}|null>(null);const filtered=(check?.date===date?check.slots:[]).filter(s=>(!x.time_from||s.time>=String(x.time_from).slice(0,5))&&(!x.time_to||s.time<=String(x.time_to).slice(0,5)));
 return <article><div className="bf-waitlist-person"><b>{x.customer_name}</b><span>{x.customer_phone} · {x.customer_email}</span><small>{x.services?.name} · {String(x.date_from).split("-").reverse().join(".")}{last!==x.date_from?` – ${last.split("-").reverse().join(".")}`:""}{x.time_from?` · ${String(x.time_from).slice(0,5)}–${String(x.time_to||"").slice(0,5)}`:""}</small></div><div className="bf-waitlist-actions"><label style={{display:"grid",gap:4,fontSize:12,fontWeight:700}}>Ден за проверка<select style={{minHeight:44,borderRadius:11,padding:10}} value={date} onChange={e=>{setDate(e.target.value);setSelected(null);find(x,e.target.value)}}>{dates.map(day=><option value={day} key={day}>{day.split("-").reverse().join(".")}</option>)}</select></label><button className="btn btn-primary" disabled={check?.loading} onClick={()=>find(x,date)}>{check?.loading?"Проверяваме...":"Провери свободни"}</button><button type="button" className="bf-waitlist-remove" disabled={removing} onClick={()=>remove(x)}>{removing?"Премахване...":"Премахни"}</button></div>{check?.loading?<small className="bf-waitlist-no-match" role="status">Търсим свободните часове за тази дата...</small>:filtered.length>0?<div className="bf-waitlist-slots">{filtered.map(s=><button key={`${s.time}-${s.staffId}`} type="button" disabled={assigning} className={selected?.time===s.time&&selected?.staffId===s.staffId?"selected":""} onClick={()=>setSelected(s)}>{s.time}{s.staffName?` · ${s.staffName}`:""}</button>)}</div>:check?.checked?<small className="bf-waitlist-no-match" role="status">{check.message||((check.slots.length>0)?"Няма свободен час в желания часови диапазон.":"Няма свободни часове на тази дата. Провери работния график, предварителния срок за записване и дали има свободен специалист.")}</small>:null}{selected&&<div className="bf-waitlist-confirm"><p>Записване на <b>{x.customer_name}</b> на <b>{date.split("-").reverse().join(".")} · {selected.time}</b>{selected.staffName?` при ${selected.staffName}`:""}.</p><button type="button" className="btn btn-primary" disabled={assigning} onClick={()=>assign(x,date,selected.time,selected.staffId)}>{assigning?"Записване...":"Потвърди записването"}</button><button type="button" disabled={assigning} onClick={()=>setSelected(null)}>Откажи</button></div>}{assignmentMessage&&<p className="bf-strong-message" role="alert">{assignmentMessage}</p>}</article>
}
