"use client";
import {useEffect,useState} from "react";
import AdminShell from "@/components/admin/AdminShell";
import {useBusiness} from "@/lib/beautyflow/useBusiness";
import {supabase} from "@/lib/supabase";
import LoadingScreen from "@/components/LoadingScreen";

type CheckResult={slots:any[];checked:boolean;loading:boolean;message:string};
export default function Waitlist(){
 const{business,loading}=useBusiness();const[list,setList]=useState<any[]>([]);const[msg,setMsg]=useState("");const[checks,setChecks]=useState<Record<string,CheckResult>>({});const[listLoading,setListLoading]=useState(true);const[removing,setRemoving]=useState("");
 async function load(preserveMessage=false){if(!business)return;setListLoading(true);try{const{data:{session}}=await supabase.auth.getSession();const r=await fetch(`/api/business/waitlist?salonId=${encodeURIComponent(business.id)}`,{headers:{Authorization:`Bearer ${session?.access_token||""}`},cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.message||"Не успяхме да заредим списъка.");if(!preserveMessage)setMsg("");setList(j.items||[])}catch(e){setMsg(e instanceof Error?e.message:"Не успяхме да заредим списъка.");setList([])}finally{setListLoading(false)}}
 useEffect(()=>{setListLoading(true);setChecks({});void load()},[business?.id]);
 async function find(x:any,date:string){if(!business||!date)return;setChecks(v=>({...v,[x.id]:{slots:[],checked:false,loading:true,message:""}}));try{const q=new URLSearchParams({salonId:business.id,serviceId:x.service_id,date});if(x.staff_id)q.set("staffId",x.staff_id);const r=await fetch(`/api/public/availability?${q}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.message||"Не успяхме да проверим свободните часове.");const slots=(j.timeline||[]).filter((y:any)=>y.status==="available");setChecks(v=>({...v,[x.id]:{slots,checked:true,loading:false,message:j.message||""}}))}catch(e){setChecks(v=>({...v,[x.id]:{slots:[],checked:true,loading:false,message:e instanceof Error?e.message:"Грешка при проверката."}}))}}
 async function assign(x:any,date:string,time:string,staffId?:string){if(!business||!confirm(`Да запиша ли ${x.customer_name} на ${date.split("-").reverse().join(".")} в ${time}?`))return;const{data:{session}}=await supabase.auth.getSession();const r=await fetch("/api/business/waitlist-assign",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token||""}`},body:JSON.stringify({id:x.id,date,time,staffId})});const j=await r.json();setMsg(j.message||"");if(r.ok){setChecks(v=>({...v,[x.id]:{slots:[],checked:false,loading:false,message:""}}));await load(true)}}
 async function remove(x:any){if(!confirm(`Да премахна ли ${x.customer_name} от списъка за изчакване?`))return;setRemoving(x.id);try{const{data:{session}}=await supabase.auth.getSession();const r=await fetch("/api/business/waitlist",{method:"DELETE",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token||""}`},body:JSON.stringify({id:x.id})});const j=await r.json();if(!r.ok)throw new Error(j.message||"Не успяхме да премахнем клиента.");setMsg(j.message);await load(true)}catch(e){setMsg(e instanceof Error?e.message:"Грешка при премахване.")}finally{setRemoving("")}}
 if(loading||listLoading)return <LoadingScreen title="Зареждане..." subtitle="Зареждаме списъка за изчакване"/>;
 return <AdminShell><header className="dash-header"><div><span className="eyebrow">ИЗЧАКВАНЕ</span><h1>Списък за изчакване</h1><p>Всеки чакащ е за конкретна дата и услуга. Когато се освободи подходящ час, добави клиента директно.</p></div></header>{msg&&<p className="form-message bf-strong-message">{msg}</p>}<section className="dash-card"><div className="bf-waitlist-admin">{list.length===0?<div className="dash-empty">Няма чакащи клиенти.</div>:list.map(x=><WaitRow key={x.id} x={x} check={checks[x.id]} find={find} assign={assign} remove={remove} removing={removing===x.id}/>)}</div></section></AdminShell>
}
function WaitRow({x,check,find,assign,remove,removing}:{x:any;check?:CheckResult;find:(x:any,date:string)=>void;assign:(x:any,date:string,time:string,staffId?:string)=>void;remove:(x:any)=>void;removing:boolean}){
 const date=String(x.date_from);const filtered=(check?.slots||[]).filter(s=>(!x.time_from||s.time>=String(x.time_from).slice(0,5))&&(!x.time_to||s.time<=String(x.time_to).slice(0,5)));
 return <article><div className="bf-waitlist-person"><b>{x.customer_name}</b><span>{x.customer_phone} · {x.customer_email}</span><small>{x.services?.name} · {date.split("-").reverse().join(".")}{x.time_from?` · ${String(x.time_from).slice(0,5)}–${String(x.time_to||"").slice(0,5)}`:""}</small></div><div className="bf-waitlist-actions"><strong className="bf-waitlist-fixed-date">{date.split("-").reverse().join(".")}</strong><button className="btn btn-primary" disabled={check?.loading} onClick={()=>find(x,date)}>{check?.loading?"Проверяваме...":"Провери свободни"}</button><button type="button" className="bf-waitlist-remove" disabled={removing} onClick={()=>remove(x)}>{removing?"Премахване...":"Премахни"}</button></div>{check?.loading?<small className="bf-waitlist-no-match" role="status">Търсим свободните часове за тази дата...</small>:filtered.length>0?<div className="bf-waitlist-slots">{filtered.map(s=><button key={`${s.time}-${s.staffId}`} onClick={()=>assign(x,date,s.time,s.staffId)}>{s.time}{s.staffName?` · ${s.staffName}`:""}</button>)}</div>:check?.checked?<small className="bf-waitlist-no-match" role="status">{check.message||((check.slots.length>0)?"Няма свободен час в желания часови диапазон.":"Няма свободни часове на тази дата. Провери работния график, предварителния срок за записване и дали има свободен специалист.")}</small>:null}</article>
}
