"use client";
import {useEffect,useRef,useState}from"react";
import {useSearchParams}from"next/navigation";
import Link from"next/link";import Image from"next/image";
import PublicNav from"@/components/PublicNav";
import Footer from"@/components/Footer";
import LoadingScreen from"@/components/LoadingScreen";
import {BEAUTY_CATEGORIES,categoryLabel}from"@/lib/beautyflow/categories";
type Salon={id:string;name:string;slug:string;city:string|null;category:string|null;description:string|null;logo_url:string|null;cover_url:string|null;logo_position_x?:number|null;logo_position_y?:number|null;cover_position_x?:number|null;cover_position_y?:number|null};
export default function Salons(){
 const searchParams=useSearchParams();
 const initialCategory=searchParams.get("category")||"all";
 const[all,setAll]=useState<Salon[]>([]);const[q,setQ]=useState("");const[debouncedQ,setDebouncedQ]=useState("");const[cat,setCat]=useState(initialCategory);const[page,setPage]=useState(1);const[total,setTotal]=useState(0);const[loading,setLoading]=useState(true);const[hasLoaded,setHasLoaded]=useState(false);const[error,setError]=useState("");const[catOpen,setCatOpen]=useState(false);const catRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{const next=searchParams.get("category")||"all";setCat(next);setPage(1)},[searchParams]);
 useEffect(()=>{const timer=window.setTimeout(()=>setDebouncedQ(q.trim()),250);return()=>window.clearTimeout(timer)},[q]);
 useEffect(()=>{const fn=(e:MouseEvent)=>{if(catRef.current&&!catRef.current.contains(e.target as Node))setCatOpen(false)};document.addEventListener("mousedown",fn);return()=>document.removeEventListener("mousedown",fn)},[]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError("");setAll([]);const params=new URLSearchParams({page:String(page)});if(cat!=="all")params.set("category",cat);if(debouncedQ)params.set("q",debouncedQ);(async()=>{try{const r=await fetch(`/api/public/salons?${params}`,{cache:"no-store",signal:controller.signal});const j=await r.json();if(!r.ok)throw new Error(j.message||"Грешка при зареждане.");if(controller.signal.aborted)return;setAll((j.salons||[])as Salon[]);setTotal(Number(j.total)||0);if(page>1&&!j.salons?.length&&j.total>0)setPage(Math.max(1,Math.ceil(j.total/12)))}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Грешка при зареждане.")}finally{if(!controller.signal.aborted){setLoading(false);setHasLoaded(true)}}})();return()=>controller.abort()},[page,cat,debouncedQ]);
 const list=all;const totalPages=Math.max(1,Math.ceil(total/12));
 const changePage=(next:number)=>{setPage(next);window.scrollTo({top:0,behavior:"smooth"})};
 const selectedLabel=cat==="all"?"Всички категории":BEAUTY_CATEGORIES.find(c=>c.value===cat)?.label||"Категория";
 if(loading&&!hasLoaded)return <LoadingScreen title="Зареждане..." subtitle="Откриваме BeautyFlow бизнесите"/>;
 return <main className="page"><PublicNav/><section className="directory-hero"><div className="container"><span className="eyebrow">BEAUTYFLOW САЛОНИ</span><h1>Намери твоето място.</h1><p>Барбър, фризьор, миглопластика, маникюр, масаж и още — на едно място.</p><div className="directory-tools"><input className="directory-search" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Търси по име, град или описание..."/><div className={`directory-category-menu ${catOpen?"open":""}`} ref={catRef}><button type="button" className="directory-category-trigger" onClick={()=>setCatOpen(v=>!v)}><span>{selectedLabel}</span><b>⌄</b></button>{catOpen&&<div className="directory-category-popover"><button type="button" className={cat==="all"?"active":""} onClick={()=>{setCat("all");setPage(1);setCatOpen(false)}}>Всички категории</button>{BEAUTY_CATEGORIES.map(c=><button type="button" key={c.value} className={cat===c.value?"active":""} onClick={()=>{setCat(c.value);setPage(1);setCatOpen(false)}}>{c.label}</button>)}</div>}</div></div></div></section><section className="container directory-body">{loading?<div className="empty-state" role="status"><h2>Зареждаме салоните...</h2></div>:error?<div className="empty-state"><h2>Не успяхме да заредим салоните.</h2><p>{error}</p></div>:list.length===0?<div className="empty-state"><h2>Все още няма бизнеси тук.</h2><p>{cat==="all"&&!debouncedQ?"Одобрените и активни BeautyFlow профили ще се появят тук автоматично.":"Няма резултат за избрания филтър."}</p></div>:<div className="salon-grid">{list.map(s=>{const cx=Number(s.cover_position_x??50),cy=Number(s.cover_position_y??50),lx=Number(s.logo_position_x??50),ly=Number(s.logo_position_y??50);return <Link href={`/salon/${s.slug}`} className={`salon-card cat-${s.category||"other"}`} key={s.id}><div className="salon-card-cover">{s.cover_url&&<Image src={s.cover_url} alt="" fill sizes="(max-width: 640px) 100vw, (max-width: 1000px) 50vw, 360px" quality={72} unoptimized={!process.env.NEXT_PUBLIC_SUPABASE_URL} style={{objectFit:"cover",objectPosition:`${cx}% ${cy}%`}}/>}<span>{categoryLabel(s.category)}</span></div><div className="salon-card-body"><div className="salon-card-title"><div>{s.logo_url?<Image src={s.logo_url} alt="" width={96} height={96} sizes="96px" quality={72} unoptimized={!process.env.NEXT_PUBLIC_SUPABASE_URL} style={{objectPosition:`${lx}% ${ly}%`}}/>:<b>{s.name.slice(0,1)}</b>}</div><section><h3>{s.name}</h3><p>{s.city||"България"}</p></section></div><p>{s.description||"BeautyFlow профил"}</p><strong>Разгледай и запази час →</strong></div></Link>})}</div>}{!loading&&!error&&totalPages>1&&<nav className="bf-directory-pages" aria-label="Страници със салони"><button type="button" onClick={()=>changePage(page-1)} disabled={page<=1}>← Предишна</button><span>Страница {page} от {totalPages}</span><button type="button" onClick={()=>changePage(page+1)} disabled={page>=totalPages}>Следваща →</button></nav>}</section><Footer/></main>
}
