"use client";
import { useEffect,useState } from "react";
import OwnerShell from "@/components/OwnerShell";
import OwnerPageFrameEditor,{PageFrames} from "@/components/OwnerPageFrameEditor";
import { supabase } from "@/lib/supabase";

type FormState={background_url:string;background_position:string};
export default function OwnerDesign(){
 const[state,setState]=useState<FormState>({background_url:"/brand/beautyflow-background.png",background_position:"center top"});
 const[preview,setPreview]=useState("");const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);const[setup,setSetup]=useState(false);const[pageFrames,setPageFrames]=useState<PageFrames>({});const[frameFiles,setFrameFiles]=useState<Record<string,File>>({});
 async function token(){return (await supabase.auth.getSession()).data.session?.access_token||""}
 useEffect(()=>{try{const c=localStorage.getItem("bf_platform_design_cache");if(c){const j=JSON.parse(c);if(j.page_frames)setPageFrames(j.page_frames)}}catch{};(async()=>{const r=await fetch("/api/owner/design",{headers:{Authorization:`Bearer ${await token()}`},cache:"no-store"});const j=await r.json();setState({background_url:j.background_url||"",background_position:j.background_position||"center top"});setPreview(j.background_url||"");if(j.page_frames&&Object.keys(j.page_frames).length)setPageFrames(j.page_frames);setSetup(Boolean(j.setupRequired));if(j.message)setMsg(j.message)})()},[]);
 function choose(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(f){const u=URL.createObjectURL(f);setPreview(u)}}
 function frameFile(id:string,file:File|null){setFrameFiles(s=>{const n={...s};if(file)n[id]=file;else delete n[id];return n})}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const f=new FormData(e.currentTarget);f.set("page_frames",JSON.stringify(pageFrames));Object.entries(frameFiles).forEach(([id,file])=>f.append(`frame_file__${id}`,file));const r=await fetch("/api/owner/design",{method:"POST",headers:{Authorization:`Bearer ${await token()}`},body:f});const j=await r.json();setMsg(j.message||"");if(r.ok){const saved={...j,page_frames:j.page_frames||pageFrames};setState(s=>({...s,background_url:j.background_url||""}));setPreview(j.background_url||"");setPageFrames(saved.page_frames);setFrameFiles({});setSetup(false);try{localStorage.setItem("bf_platform_design_cache",JSON.stringify(saved));window.dispatchEvent(new CustomEvent("bf-design-updated",{detail:saved}))}catch{}}else{try{const local={background_url:state.background_url,background_position:state.background_position,overlay_opacity:0,page_frames:pageFrames};localStorage.setItem("bf_platform_design_cache",JSON.stringify(local));window.dispatchEvent(new CustomEvent("bf-design-updated",{detail:local}))}catch{}}setBusy(false)}
 return <OwnerShell><div className="owner-title"><div><span>PLATFORM DESIGN</span><h1>Визия на сайта</h1><p>Глобален фон и отделна визуална композиция за всяка страница.</p></div></div>
 <form onSubmit={save} className="owner-design-form"><div className="design-admin-grid"><div className="design-admin-card"><h2>Глобален фон</h2><p className="design-help">Снимките се използват без филтър, без opacity и без изсветляване.</p>{setup&&<div className="owner-notice">Пусни <b>platform-design-v2.37.sql</b> в Supabase SQL Editor, за да запазваш рамките по страници.</div>}<div className="field"><label>Качи фон</label><input name="background_file" type="file" accept="image/*" onChange={choose}/></div><div className="field"><label>Или URL на фон</label><input name="background_url" value={state.background_url} onChange={e=>{setState({...state,background_url:e.target.value});setPreview(e.target.value)}} placeholder="https://..."/></div><div className="field"><label>Позиция</label><select name="background_position" value={state.background_position} onChange={e=>setState({...state,background_position:e.target.value})}><option value="center top">Център / горе</option><option value="center center">Център</option><option value="left top">Ляво / горе</option><option value="right top">Дясно / горе</option></select></div></div><div className="design-preview-card"><span>LIVE PREVIEW</span><div className="design-preview" style={{backgroundImage:preview?`url(${preview})`:undefined,backgroundPosition:state.background_position}}><div className="design-preview-copy"><b>Beauty<span>Flow</span></b><h3>Контрол върху времето.<br/><strong>Свобода за стила.</strong></h3></div></div><small>Фонът се показва точно както е качен.</small></div></div><OwnerPageFrameEditor value={pageFrames} onChange={setPageFrames} onFile={frameFile}/><div className="owner-design-save"><button className="btn btn-dark" disabled={busy}>{busy?"Запазване...":"Запази цялата визия"}</button>{msg&&<div className="owner-notice">{msg}</div>}</div></form></OwnerShell>
}
