"use client";
import{useEffect,useMemo,useState}from"react";
import AdminShell from"@/components/admin/AdminShell";
import AdminDatePicker from"@/components/AdminDatePicker";
import LoadingScreen from"@/components/LoadingScreen";
import{useBusiness}from"@/lib/beautyflow/useBusiness";
import{isoToday}from"@/lib/beautyflow/date";
import{supabase}from"@/lib/supabase";
const OUTCOMES=[{id:"completed",label:"Завършен"},{id:"late",label:"Закъснял"},{id:"cancelled",label:"Отказан"},{id:"no_show",label:"Не дошъл"}];
const CLIENT_LABEL:any={regular:"Редовен",late:"Закъснявал",cancelled:"Отказвал",no_show:"Не дошъл",blacklist:"Черен списък"};
const phoneKey=(v:string)=>String(v||"").replace(/[^0-9+]/g,"");
const mins=(t:string)=>{const[h,m]=String(t||"00:00").slice(0,5).split(":").map(Number);return h*60+m};
const clock=(n:number)=>`${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`;
export default function Calendar(){
 const{business,loading:businessLoading,staffId,isOwner}=useBusiness();const[date,setDate]=useState(isoToday());const[list,setList]=useState<any[]>([]);const[draft,setDraft]=useState<Record<string,string>>({});const[flags,setFlags]=useState<Record<string,string>>({});const[saving,setSaving]=useState("");const[deleting,setDeleting]=useState("");const[loading,setLoading]=useState(true);const[work,setWork]=useState<any|null>(null);
 async function load(){if(!business)return;setLoading(true);const weekday=new Date(`${date}T12:00:00`).getDay();let appointmentsQuery=supabase.from("appointments").select("*,services(name),staff(name)").eq("salon_id",business.id).eq("appointment_date",date).order("start_time");if(!isOwner&&staffId)appointmentsQuery=appointmentsQuery.eq("staff_id",staffId);let hoursQuery:any=supabase.from("working_hours").select("weekday,enabled,start_time,end_time").eq("salon_id",business.id).eq("weekday",weekday);if(!isOwner&&staffId)hoursQuery=supabase.from("staff_working_hours").select("weekday,enabled,start_time,end_time").eq("salon_id",business.id).eq("staff_id",staffId).eq("weekday",weekday);const[{data},{data:hours}]=await Promise.all([appointmentsQuery,hoursQuery.maybeSingle()]);const rows=data||[];setList(rows);setWork(hours||null);setDraft({});const phones=[...new Set(rows.map((a:any)=>phoneKey(a.customer_phone)).filter(Boolean))];if(phones.length){const{data:customers}=await supabase.from("salon_customers").select("phone_normalized,status").eq("salon_id",business.id).in("phone_normalized",phones);setFlags(Object.fromEntries((customers||[]).map((x:any)=>[x.phone_normalized,x.status])))}else setFlags({});setLoading(false)}
 useEffect(()=>{load()},[business,date,staffId,isOwner]);
 const times=useMemo(()=>{if(!work?.enabled)return[];const start=mins(work.start_time),end=mins(work.end_time);const out:string[]=[];for(let t=start;t<=end;t+=15)out.push(clock(t));return out},[work]);
 async function saveStatus(a:any){const next=draft[a.id];if(!next||!business)return;setSaving(a.id);const normalized=phoneKey(a.customer_phone),clientStatus=next==="completed"?"regular":next;const[{error:e1},{error:e2}]=await Promise.all([supabase.from("appointments").update({status:next}).eq("id",a.id),supabase.from("salon_customers").upsert({salon_id:business.id,phone_normalized:normalized,customer_name:a.customer_name,customer_phone:a.customer_phone,customer_email:a.customer_email||null,status:clientStatus,updated_at:new Date().toISOString()},{onConflict:"salon_id,phone_normalized"})]);setSaving("");if(!e1&&!e2)load()}
 async function deleteAppointment(a:any){if(!business||!confirm(`Да изтрием ли часа на ${a.customer_name} в ${String(a.start_time).slice(0,5)}?\nЧасът ще се освободи веднага.`))return;setDeleting(a.id);const{error}=await supabase.from("appointments").delete().eq("id",a.id).eq("salon_id",business.id);setDeleting("");if(error){alert("Не успяхме да изтрием часа. Опитай отново.");return}load()}
 if(businessLoading||(business&&loading))return <LoadingScreen title="Зареждане..." subtitle="Подреждаме дневния календар"/>;
 const visibleTimes=times.filter(t=>!list.some(a=>mins(a.start_time)<mins(t)&&mins(t)<mins(a.end_time)));
 return <AdminShell><header className="dash-header"><div><span className="eyebrow">КАЛЕНДАР</span><h1>Дневен календар</h1><p>Календарът следва реалното работно време за избрания ден.</p></div><AdminDatePicker className="date-control-bg" value={date} onChange={setDate}/></header><section className="calendar-day">{!work?.enabled?<div className="dash-empty">Този ден е отбелязан като почивен.</div>:<div className="calendar-hours">{visibleTimes.map(t=>{const a=list.find(v=>v.start_time.slice(0,5)===t),flag=a?flags[phoneKey(a.customer_phone)]||"regular":"regular";return <div key={t} className={a?`busy client-${flag}`:""}><time>{t}</time>{a?<section className="calendar-appointment"><div className="calendar-client-head"><div><b className="calendar-service-name">{a.services?.name||"Услуга"}</b><span className="calendar-customer-name">{a.customer_name}{a.staff?.name?` · ${a.staff.name}`:""}</span><small className="calendar-duration">{String(a.start_time).slice(0,5)} – {String(a.end_time).slice(0,5)}</small></div><span className={`client-status-dot client-${flag}`}>{CLIENT_LABEL[flag]||"Редовен"}</span></div>{a.note&&<details className="appointment-note"><summary>📝 Подробности</summary><p>{a.note}</p></details>}<div className="appointment-reaction-zone"><div className="appointment-reaction-title"><b>Реакция към посещението</b><span>Избери как е преминал този час.</span></div><div className="appointment-status-picker">{OUTCOMES.map(s=><button type="button" key={s.id} className={`status-choice status-${s.id} ${draft[a.id]===s.id?"selected":""}`} onClick={()=>setDraft(v=>({...v,[a.id]:s.id}))}>{s.label}</button>)}</div></div><div className="calendar-save-zone"><span>След избор запази промяната за клиента.</span><div className="calendar-appointment-actions"><button type="button" className="save-status-btn" disabled={saving===a.id||!draft[a.id]} onClick={()=>saveStatus(a)}>{saving===a.id?"Запазване...":"Запази"}</button><button type="button" className="delete-appointment-btn" disabled={deleting===a.id} onClick={()=>deleteAppointment(a)}>{deleting===a.id?"Изтриване...":"Изтрий часа"}</button></div></div></section>:<span>Свободно</span>}</div>})}</div>}</section></AdminShell>;
}
