"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase";
import {useBusiness} from "@/lib/beautyflow/useBusiness";
type FeedItem={id:string;customer_name:string;appointment_date:string;start_time:string;created_at?:string;note?:string|null;services?:{name?:string}|null};
export default function AdminNotifications(){
 const{business,staffId}=useBusiness();const[open,setOpen]=useState(false);const[items,setItems]=useState<FeedItem[]>([]);const[unread,setUnread]=useState(0);const ref=useRef<HTMLDivElement>(null);
 const storageKey=business?.id?`beautyflow.notifications.seen.v7.${business.id}.${staffId||"personal"}`:"";
 const newest=(rows:FeedItem[])=>rows.map(x=>String(x.created_at||"")).filter(Boolean).sort().at(-1)||"";
 function calculateUnread(rows:FeedItem[]){if(!storageKey||typeof window==="undefined")return;const seen=window.localStorage.getItem(storageKey);if(!seen){setUnread(rows.length);return}setUnread(rows.filter(x=>String(x.created_at||"")>seen).length)}
 async function load(){if(!business)return;const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token){setItems([]);setUnread(0);return}const r=await fetch(`/api/business/staff-notifications?salonId=${encodeURIComponent(business.id)}`,{headers:{Authorization:`Bearer ${session.access_token}`},cache:"no-store"});const j=await r.json().catch(()=>({}));if(!r.ok){console.error("BeautyFlow personal notifications failed",j.message);setItems([]);setUnread(0);return}const rows=(j.items||[]) as FeedItem[];setItems(rows);calculateUnread(rows)}
 function markSeen(){if(!storageKey||typeof window==="undefined")return;const latest=newest(items)||new Date().toISOString();window.localStorage.setItem(storageKey,latest);setUnread(0)}
 useEffect(()=>{void load()},[business,staffId]);
 useEffect(()=>{if(!business)return;const ch=supabase.channel(`beautyflow-personal-feed-${business.id}-${staffId||"none"}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"appointments",filter:`salon_id=eq.${business.id}`},(payload:any)=>{if(!staffId||payload?.new?.staff_id!==staffId)return;void load()}).subscribe();return()=>{supabase.removeChannel(ch)}},[business,staffId]);
 useEffect(()=>{const close=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setOpen(false)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);
 const fmt=(d:string)=>new Date(`${d}T12:00:00`).toLocaleDateString("bg-BG",{day:"2-digit",month:"2-digit"}),badge=unread>9?"9+":String(unread);
 return <div className="admin-notify" ref={ref}><button type="button" className="admin-notify-btn" aria-label={unread?`Известия, ${unread} нови`:"Известия"} onClick={()=>{const next=!open;setOpen(next);if(next)markSeen()}}>🔔{unread>0&&<b>{badge}</b>}</button>{open&&<div className="admin-notify-popover"><div className="admin-notify-head"><div><strong>Live feed</strong><span>Моите записвания в реално време</span></div><button type="button" onClick={()=>setOpen(false)}>×</button></div><div className="admin-notify-list">{items.length===0?<p>Все още няма твои записвания.</p>:items.map(x=>{const note=String(x.note||"").trim();return <Link key={x.id} href="/admin/bookings" onClick={()=>setOpen(false)}><i className="feed-dot">●</i><div className="admin-notify-main"><b>👤 {x.customer_name}</b><span>✂️ {x.services?.name||"Резервация"}</span><small>{note?"📝 Има подробности":"Без подробности"}</small>{note&&<small className="notify-note-preview">{note}</small>}</div><div className="admin-notify-when"><strong>📅 {fmt(x.appointment_date)}</strong><em>🕒 {String(x.start_time).slice(0,5)}</em></div></Link>})}</div><Link className="admin-notify-all" href="/admin/bookings" onClick={()=>setOpen(false)}>Виж моите записвания →</Link></div>}</div>
}