"use client";
import Link from"next/link";
import{usePathname,useRouter}from"next/navigation";
import{useEffect,useRef,useState}from"react";
import{supabase}from"@/lib/supabase";
import{useBusiness}from"@/lib/beautyflow/useBusiness";
import AdminNotifications from"@/components/admin/AdminNotifications";
const ownerLinks=[["/admin","Начало"],["/admin/calendar","Календар"],["/admin/bookings","Записвания"],["/admin/services","Услуги"],["/admin/staff","Екип"],["/admin/customers","Клиенти"],["/admin/schedule","График"],["/admin/my-profile","Моят профил"],["/admin/settings","Профил"]];
const staffLinks=[["/admin","Начало"],["/admin/calendar","Календар"],["/admin/bookings","Записвания"],["/admin/schedule","График"],["/admin/my-profile","Моят профил"]];
export default function AdminShell({children}:{children:React.ReactNode}){
 const path=usePathname(),router=useRouter(),{business,isOwner}=useBusiness(),[menu,setMenu]=useState(false),ref=useRef<HTMLDivElement>(null);const links=isOwner?ownerLinks:staffLinks;const theme=(path.split("/")[2]||"home").replace(/[^a-z-]/g,"");
 useEffect(()=>{const close=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setMenu(false)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);
 async function logout(){await supabase.auth.signOut();router.replace("/login")}
 return <main className={`dash-page dash-theme-${theme}`}><div className="dash-main"><div className="admin-menu-bar" ref={ref}><Link href="/admin" className="admin-menu-brand"><img src="/beautyflow-logo-circle.png" alt="BeautyFlow"/><span><b>BeautyFlow</b><small>{business?.name||"BUSINESS"}</small></span></Link><div className="admin-top-actions"><AdminNotifications/><button type="button" className={`admin-menu-trigger ${menu?"active":""}`} onClick={()=>setMenu(v=>!v)}>☰ Меню</button></div>{menu&&<div className="admin-menu-popover"><div className="mobile-admin-menu-head"><b>Админ меню</b><button type="button" onClick={()=>setMenu(false)}>×</button></div>{links.map(([href,label])=><Link key={href} href={href} onClick={()=>setMenu(false)} className={path===href||href!=="/admin"&&path.startsWith(href)?"active":""}>{label}</Link>)}<div className="admin-menu-separator"/><Link href={business?`/salon/${business.slug}`:"/salons"} onClick={()=>setMenu(false)}>Виж публичната страница</Link><Link href="/" onClick={()=>setMenu(false)}>Към BeautyFlow</Link><button type="button" className="admin-menu-logout" onClick={logout}>Изход</button></div>}</div>{children}<nav className="bf-admin-bottom-nav" aria-label="Бърза навигация"><Link href="/admin" className={path==="/admin"?"active":""}><span>⌂</span><b>Начало</b></Link><Link href="/admin/bookings" className={path.startsWith("/admin/bookings")?"active":""}><span>▣</span><b>Записи</b></Link><Link href={isOwner?"/admin/settings":"/admin/my-profile"} className={path.startsWith(isOwner?"/admin/settings":"/admin/my-profile")?"active":""}><span>○</span><b>Профил</b></Link></nav></div></main>
}
