import{NextResponse}from"next/server";import{getSupabaseAdmin}from"@/lib/supabaseAdmin";import{toMinutes,fromMinutes,overlaps}from"@/lib/beautyflow/time";import{sofiaNow,localWallMinutes,parseIsoDate}from"@/lib/beautyflow/clock";import{canCreateBeautyFlowBookings}from"@/lib/beautyflow/subscription";
type TimelineSlot={time:string;status:"available"|"booked"|"unavailable";staffId?:string;staffName?:string};
export async function GET(req:Request){try{const u=new URL(req.url),salonId=u.searchParams.get("salonId")||"",serviceId=u.searchParams.get("serviceId")||"",requestedStaffId=u.searchParams.get("staffId")||"",date=u.searchParams.get("date")||"";if(!salonId||!serviceId||!date)return NextResponse.json({slots:[],timeline:[]});const db=getSupabaseAdmin(),weekday=new Date(`${date}T12:00:00`).getDay();
 const[{data:salon},{data:service},{data:settings},{data:salonHours},{data:salonOff},{data:staffRows},{data:serviceLinks},{data:staffHours},{data:staffOff},{data:apps}]=await Promise.all([
  db.from("salons").select("active,subscription_status,subscription_ends_at,trial_ends_at").eq("id",salonId).maybeSingle(),
  db.from("services").select("id,duration_min,buffer_min").eq("id",serviceId).eq("salon_id",salonId).eq("active",true).maybeSingle(),
  db.from("booking_settings").select("*").eq("salon_id",salonId).maybeSingle(),
  db.from("working_hours").select("*").eq("salon_id",salonId).eq("weekday",weekday).maybeSingle(),
  db.from("time_off").select("*").eq("salon_id",salonId).eq("off_date",date),
  db.from("staff").select("id,name,active").eq("salon_id",salonId).eq("active",true).order("name"),
  db.from("staff_services").select("staff_id,service_id").eq("salon_id",salonId).eq("service_id",serviceId),
  db.from("staff_working_hours").select("*").eq("salon_id",salonId).eq("weekday",weekday),
  db.from("staff_time_off").select("*").eq("salon_id",salonId).eq("off_date",date),
  db.from("appointments").select("start_time,end_time,staff_id,status").eq("salon_id",salonId).eq("appointment_date",date).neq("status","cancelled")
 ]);
 if(!salon?.active||!canCreateBeautyFlowBookings(salon))return NextResponse.json({slots:[],timeline:[],bookingUnavailable:true,message:"Онлайн записването временно не е достъпно."},{status:403});
 if(!service)return NextResponse.json({slots:[],timeline:[]});
 const allStaff=staffRows||[],linked=new Set((serviceLinks||[]).map((x:any)=>x.staff_id));let eligible=allStaff.filter((s:any)=>linked.size===0||linked.has(s.id));if(requestedStaffId)eligible=eligible.filter((s:any)=>s.id===requestedStaffId);if(!eligible.length)return NextResponse.json({slots:[],timeline:[]});
 const now=sofiaNow(),minNotice=Number(settings?.min_notice_minutes??Math.max(Number(settings?.min_notice_hours||0)*60,180)),maxDays=settings?.max_advance_days||60,requested=parseIsoDate(date),days=Math.floor((localWallMinutes(requested.year,requested.month,requested.day)-localWallMinutes(now.year,now.month,now.day))/1440);if(days<0||days>maxDays)return NextResponse.json({slots:[],timeline:[]});
 if((salonOff||[]).some((x:any)=>x.all_day))return NextResponse.json({slots:[],timeline:[]});const globalOff=(salonOff||[]).filter((x:any)=>!x.all_day&&x.start_time&&x.end_time).map((x:any)=>[toMinutes(x.start_time),toMinutes(x.end_time)] as [number,number]);const dur=Number(service.duration_min)+Number(service.buffer_min||0),step=15;
 const perStaff=eligible.map((st:any)=>{const ownHours=(staffHours||[]).find((h:any)=>h.staff_id===st.id);const h=ownHours||salonHours;if(!h?.enabled)return{staff:st,slots:new Set<string>()};const start=toMinutes(h.start_time),end=toMinutes(h.end_time);const ownOff=(staffOff||[]).filter((x:any)=>x.staff_id===st.id);if(ownOff.some((x:any)=>x.all_day))return{staff:st,slots:new Set<string>()};const offBlocks=[...globalOff,...ownOff.filter((x:any)=>!x.all_day&&x.start_time&&x.end_time).map((x:any)=>[toMinutes(x.start_time),toMinutes(x.end_time)] as [number,number])];const occupied=(apps||[]).filter((a:any)=>!a.staff_id||a.staff_id===st.id).map((a:any)=>[toMinutes(a.start_time),toMinutes(a.end_time)] as [number,number]);const slots=new Set<string>();for(let t=start;t+dur<=end;t+=step){const past=days===0&&t<now.hour*60+now.minute+minNotice;if(past)continue;if(occupied.some(([a,b])=>overlaps(t,t+dur,a,b)))continue;if(offBlocks.some(([a,b])=>overlaps(t,t+dur,a,b)))continue;slots.add(fromMinutes(t))}return{staff:st,slots}});
 const allTimes=new Set<string>();for(const x of perStaff)for(const t of x.slots)allTimes.add(t);const sorted=[...allTimes].sort();const timeline:TimelineSlot[]=sorted.map(time=>{const available=perStaff.find(x=>x.slots.has(time));return available?{time,status:"available",staffId:available.staff.id,staffName:available.staff.name}:{time,status:"unavailable"}});return NextResponse.json({slots:sorted,timeline,eligibleStaff:eligible.map((s:any)=>({id:s.id,name:s.name}))});
 }catch(e){return NextResponse.json({message:e instanceof Error?e.message:"Грешка",slots:[],timeline:[]},{status:500})}}
