"use client";
import{useEffect,useMemo,useState}from"react";import AdminShell from"@/components/admin/AdminShell";import{useBusiness}from"@/lib/beautyflow/useBusiness";import{supabase}from"@/lib/supabase";import LoadingScreen from"@/components/LoadingScreen";
const LABEL:any={regular:"Редовен",late:"Закъснявал",cancelled:"Отказвал",no_show:"Не дошъл",blacklist:"Черен списък"};
const phoneKey=(v:string)=>String(v||"").replace(/[^0-9+]/g,"");
export default function Customers(){
 const{business,loading:businessLoading}=useBusiness();const[list,setList]=useState<any[]>([]);const[loading,setLoading]=useState(true);
 async function load(){if(!business)return;setLoading(true);const[{data:apps},{data:stored}]=await Promise.all([supabase.from("appointments").select("customer_name,customer_phone,customer_email,appointment_date,status").eq("salon_id",business.id).order("appointment_date",{ascending:false}),supabase.from("salon_customers").select("*").eq("salon_id",business.id)]);const statuses=new Map<string,any>();for(const row of stored||[])statuses.set(row.phone_normalized,row);const map=new Map<string,any>();for(const a of apps||[]){const k=phoneKey(a.customer_phone);if(!k)continue;const saved=statuses.get(k);const x=map.get(k)||{...a,phone_normalized:k,visits:0,status:saved?.status||"regular"};if(a.status==="completed"||a.status==="late")x.visits++;if(saved){x.status=saved.status;x.customer_name=saved.customer_name||x.customer_name;x.customer_email=saved.customer_email||x.customer_email}map.set(k,x)}for(const x of stored||[]){if(!map.has(x.phone_normalized))map.set(x.phone_normalized,{...x,visits:0})}setList([...map.values()]);setLoading(false)}
 useEffect(()=>{load()},[business]);
 const regular=useMemo(()=>list.filter(x=>!["cancelled","no_show","blacklist"].includes(x.status)),[list]);const black=useMemo(()=>list.filter(x=>["cancelled","no_show","blacklist"].includes(x.status)),[list]);
 if(businessLoading||(business&&loading))return <LoadingScreen title="Зареждане..." subtitle="Зареждаме клиентите"/>;
 async function move(x:any,status:string){if(!business)return;await supabase.from("salon_customers").upsert({salon_id:business.id,phone_normalized:x.phone_normalized,customer_name:x.customer_name,customer_phone:x.customer_phone,customer_email:x.customer_email||null,status,updated_at:new Date().toISOString()},{onConflict:"salon_id,phone_normalized"});load()}
 function cards(rows:any[],empty:string,isBlack=false){return <div className="customer-grid">{rows.length===0?<div className="dash-empty">{empty}</div>:rows.map(x=><div key={x.phone_normalized} className={`customer-card client-${x.status}`}><div>{x.customer_name.slice(0,1)}</div><section><b>{x.customer_name}</b><span>{x.customer_phone}</span><small>{x.customer_email||"Без email"}</small><em>{LABEL[x.status]||"Редовен"}</em></section><strong>{x.visits} посещения</strong><button className={isBlack?"customer-move regular":"customer-move blacklist"} onClick={()=>move(x,isBlack?"regular":"blacklist")}>{isBlack?"Върни в редовни":"Черен списък"}</button></div>)}</div>}
 return <AdminShell><header className="dash-header"><div><span className="eyebrow">КЛИЕНТИ</span><h1>Клиенти</h1><p>Последният запазен статус се пази и при следващо записване клиентът се разпознава автоматично.</p></div></header><div className="customer-columns"><section className="dash-card customer-regular"><h2>Редовни</h2><p className="section-help">Нормални клиенти и клиенти, отбелязани като закъснели.</p>{cards(regular,"Все още няма редовни клиенти.")}</section><section className="dash-card customer-blacklist"><h2>Черен списък</h2><p className="section-help">Отказали, неявили се или добавени ръчно. Списъкът може да се променя по всяко време.</p>{cards(black,"Няма клиенти в черния списък.",true)}</section></div></AdminShell>
}
